[package]
name = "algofuzz"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.34.0"
ndarray = "0.16.1"
num_cpus = "1.17.0"
threadpool = "1.8.1"

[profile.release]
debug = true

[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1
strip = true
panic = "abort"
#build-std-features = "panic_immediate_abort"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]